---
title: "Markdown for Newbies: A Tutorial"
author: "Joshua Megnauth"
date: "March 12, 2020"
output:
  html_document:
    theme: darkly
    highlight: zenburn
    df_print: paged
---

# What is R Markdown?

[R Markdown](https://bookdown.org/yihui/rmarkdown/) is a simple and efficient [markup](https://en.wikipedia.org/wiki/Lightweight_markup_language) language designed for technical documents. R Markdown is a variation on the more general [Markdown](https://commonmark.org/) specification. I will use the two terms interchangeably in this document.

Markup languages provide small syntaxes that "markup" documents to indicate elements of presentation. Consider jotting down notes for class (or notes to pass to a friend in class)---you may underline or box terms for emphasis. In other words, you mark up your text! Marking up text may be as simple as highlighting terms or more elaborate such as using tables to categorize information.

You've likely encountered markup languages or have even used a few in your internet adventures. Hypertext Markup Language (HTML) is probably _the_ pervasive example of markup. [Media Wiki](https://www.mediawiki.org/wiki/MediaWiki) (Wikipedia and others) defines a [markup language](https://en.wikipedia.org/wiki/Wikipedia:Wiki_Markup_Language) for contributors to easily edit pages and add content that conforms to the defined standard. GitHub Pages allows Markdown via [Jekyll](https://jekyllrb.com/).

## What does that even mean?

### Efficiency

Markdown is **simple** and **efficient** because a writer (id est, you) is able to focus on producing content rather than being impeded by operational details. As a quick example we can look at **bolding** or _italicizing_ text. Bolding text in office suites, such as the open source [LibreOffice](https://www.libreoffice.org/) or Microsoft Office, involves either pressing a button with your mouse _or_ using a keyboard shortcut such as _Ctrl-B_. [LaTeX](https://www.latex-project.org/) requires subcommands in order to bold which looks a tad less tidy than Markdown.

Bolding in Markdown is as simple as surrounding text with two pairs of asterisks or two pairs of underscores:

```
**Josh likes cats.**  
__Josh likes coffee.__
```

This produces:

**Josh likes cats.**  
__Josh likes coffee.__

Easy, right? Markdown (as well as LaTeX and [Jupyter](https://www.jupyter.org)) follows the principle of _not_ distracting the writer from their content with extravagant user interfaces and cumbrous clicking. Ultimately, Markdown leads to efficient and efficacious technical document production despite having a learning curve in comparison to office suites.

### Technical Documents

The second major quality is Markdown's focus on **technical documents**. Technical documents are reports such as theses, analyses, papers, et cetera. In fact, entire books have been written entirely in Markdown. [Bookdown](https://bookdown.org/) is a project aimed at all of the wordsmiths out there who wish to write longer documents in Markdown. Hadley Wickham is a prominent R programmer who has written and contributed to salient libraries---notably [ggplot2](https://ggplot2.tidyverse.org/) as well as the [tidyverse](https://tidyverse.org/). Wickham's well-known, free, and open source text [Advanced R](http://adv-r.had.co.nz/Introduction.html) as well as his [R For Data Science](https://r4ds.had.co.nz/) were written in Bookdown and Markdown.

>"The book is written in RMarkdown with bookdown. It is automatically rebuilt from source by travis. R4DS is a collaborative effort and many people have contributed fixes and improvements via pull request."

Other notable texts include:

* [R Graphics Cookbook](https://r-graphics.org/) by Winston Chang
* [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) by Yihui Xie, J. J. Allaire, and Garrett Grolemund 
* [R for Calculus](https://dtkaplan.github.io/RforCalculus/preface.html) by [Daniel Kaplan](https://www.macalester.edu/~kaplan/) 
* [Statistical Modeling: A Fresh Approach](https://dtkaplan.github.io/SM2-bookdown/) by Daniel Kaplan 

But _why_ are so many (awesome) books written in Markdown? Good question.

Markdown allows _embedded_ and _syntax highlighted_ code blocks as well as LaTeX style mathematics symbols. Both of the aforementioned features vastly ease writing technical documents. Copying and pasting code to word processors is a task for masochists. Math often requires cumbersome extensions to properly use in G Suite or Microsoft Office. Office suites have strengths and pros, such as their ease of use---but Markdown and LaTeX are tools designed by and for scientists and engineers. Markdown files are saved as plain text rather than elaborate formats relying on XML or exotic binary representations. While plain text does not imply "technical," unknit Markdown files are easy to distribute and read without specialized tools---similar to source code, of course.

### Uh, Jupyter?

**[You may skip this section if you don't know about Jupyter.]**

Jupyter's official docs [define](https://jupyter-notebook.readthedocs.io/en/latest/notebook.html) a (Jupyter) notebook as:

>"Notebook documents contains the inputs and outputs of a interactive session as well as additional text that accompanies the code but is not meant for execution. In this way, notebook files can serve as a complete computational record of a session, interleaving executable code with explanatory text, mathematics, and rich representations of resulting objects. These documents are internally JSON files and are saved with the .ipynb extension. Since JSON is a plain text format, they can be version-controlled and shared with colleagues. <br /><br />
>Notebooks may be exported to a range of static formats, including HTML (for example, for blog posts), reStructuredText, LaTeX, PDF, and slide shows, via the nbconvert command."

Does this sound familar? _(If not you should scroll up!)_

R Markdown and Jupyter both allow writers to express their code and outcomes in the same document. The major difference is that Jupyter is tailored towards interactive use while R Markdown allows interactivity as a feature but not the primary focus. Jupyter notebooks usually run on kernels on a local or remote server. Kernels are a manifestation of an instance. For example, if you loaded a notebook exploring a delightful cat data set and another on a coffee data set, both of those would run in their own separate instance on the same server. Separate instances coupled with a server architecture allows a system where multiple people---such as students or workers---can access, create, and edit a central repository of notebooks. [JupyterHub](https://jupyterhub.readthedocs.io/en/latest/) is an open source implementation of this concept whereas [DataCamp Projects](https://www.datacamp.com/projects) is a deployment.

### Are you ready?

Anywho. Let's jump into Markdown! I will introduce some but not all features in the following sections. Consider this guide as a bootstrap after which you may look up whatever else you wish to do with Markdown with ease. I recommend [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) which is, in fact, totally definitive.

# Basic text wrangling

# A Small Discourse on Use

Jupyter and R Markdown are implementations of what is known as **computational notebooks** with the teleogical goal of **literate programming.**

The polymath Donald Knuth defines literate programming as: 
>Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a _computer_ what to do, let us concentrate rather on explaining to _human beings_ what we want a computer to do. <br />
The practitioner of literate programming can be regarded as an essayist, whose main concern is with exposition and excellence of style. Such an author, with thesaurus in hand, chooses the names of variables carefully and explains what each variable means. He or she strives for a program that is comprehensible because its concepts have been introduced in an order that is best for human understanding, using a mixture of formal and informal methods that rëınforce each other.


